### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by NobleOsinachi**

### CODE REVIEW

**Comment by Mercury2X** [comment]
Hiya

**Comment by NobleOsinachi** [comment]
> 

Hello

**Comment by Mercury2X** [comment]
Hiya, good afternoon 🌞

ShuutingStarGraphy_2x
________________________________

**Comment by Mercury2X** [comment]
Just came across your profile and I think it’s a great way

ShuutingStarGraphy_2x
________________________________

**Comment by Mercury2X** [comment]
I meant to say it’s a great way to game attention

ShuutingStarGraphy_2x
________________________________

**Pull request merged**
